import json
import os
import re
import sqlite3
from functools import lru_cache
from pathlib import Path
from typing import Any

import httpx
from fastapi import HTTPException

from app.core.config import get_agent_config, load_env_file
from app.services.csv_reader import read_csv_file

FORBIDDEN_SQL = re.compile(
    r"\b(insert|update|delete|drop|alter|create|replace|attach|detach|pragma|vacuum|truncate)\b",
    re.IGNORECASE,
)


def _add_missing_from_data(sql: str) -> str:
    if re.search(r"\bfrom\b", sql, re.IGNORECASE):
        return sql

    clause_match = re.search(
        r"\b(where|group\s+by|having|order\s+by|limit)\b",
        sql,
        re.IGNORECASE,
    )

    if clause_match:
        return f"{sql[:clause_match.start()].rstrip()} FROM data {sql[clause_match.start():].lstrip()}"

    return f"{sql} FROM data"


def validate_select_sql(sql: str, limit: int) -> str:
    cleaned = sql.strip()

    if not cleaned:
        raise HTTPException(status_code=400, detail="Generated SQL is empty.")

    if ";" in cleaned or "--" in cleaned or "/*" in cleaned or "*/" in cleaned:
        raise HTTPException(status_code=400, detail="Only a single read-only SELECT statement is allowed.")

    if not re.match(r"^\s*select\b", cleaned, re.IGNORECASE):
        raise HTTPException(status_code=400, detail="Only SELECT queries are allowed.")

    if FORBIDDEN_SQL.search(cleaned):
        raise HTTPException(status_code=400, detail="Query contains a forbidden SQL operation.")

    cleaned = _add_missing_from_data(cleaned)

    if not re.search(r'\bfrom\s+(?:"data"|data)\b', cleaned, re.IGNORECASE):
        raise HTTPException(status_code=400, detail="Query must read from the dataset table named data.")

    limit_match = re.search(r"\blimit\s+(\d+)\b", cleaned, re.IGNORECASE)
    if limit_match:
        requested_limit = int(limit_match.group(1))
        if requested_limit > limit:
            cleaned = (
                cleaned[: limit_match.start(1)]
                + str(limit)
                + cleaned[limit_match.end(1) :]
            )
    else:
        cleaned = f"{cleaned} LIMIT {limit}"

    return cleaned


def _schema_text(df) -> str:
    columns = list(df.columns)
    shown_columns = columns[:80]
    schema = ", ".join(f'"{column}" ({df[column].dtype})' for column in shown_columns)
    suffix = "" if len(columns) <= 80 else f", ... {len(columns) - 80} more columns omitted"
    return schema + suffix


@lru_cache(maxsize=32)
def _read_cached_dataframe(file_path: str, modified_time: float):
    return read_csv_file(file_path)


def _read_dataset(file_path: str):
    path = Path(file_path)
    return _read_cached_dataframe(str(path), path.stat().st_mtime)


def _configured_models(primary_model: str) -> list[str]:
    fallback_model = os.getenv("AI_AGENT_FALLBACK_MODEL", "meta/llama-3.1-8b-instruct")
    models = [primary_model, fallback_model]
    return list(dict.fromkeys(model for model in models if model))


def _request_llm_sql(
    *,
    endpoint: str,
    api_key: str,
    model: str,
    prompt: str,
    max_tokens: int,
    timeout_seconds: float,
    reasoning_effort: str | None,
) -> tuple[str, str]:
    payload = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": "You are a strict SQLite SQL generator. Output JSON only.",
            },
            {"role": "user", "content": prompt},
        ],
        "temperature": 0,
        "max_tokens": max_tokens,
        "stream": False,
    }

    if reasoning_effort:
        payload["reasoning_effort"] = reasoning_effort

    try:
        response = httpx.post(
            endpoint,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=httpx.Timeout(timeout_seconds, connect=10),
        )
    except httpx.ReadTimeout as exc:
        raise RuntimeError(f"{model} read timeout after {timeout_seconds:.0f}s") from exc
    except httpx.TimeoutException as exc:
        raise RuntimeError(f"{model} request timeout after {timeout_seconds:.0f}s") from exc

    try:
        response.raise_for_status()
    except httpx.HTTPStatusError as exc:
        detail = exc.response.text[:500]
        raise RuntimeError(f"{model} HTTP {exc.response.status_code}: {detail}") from exc

    content = response.json()["choices"][0]["message"]["content"]
    payload = _parse_json_content(content)

    if not isinstance(payload, dict) or not payload.get("sql"):
        raise RuntimeError(f"{model} response did not include a SQL statement.")

    return payload["sql"], payload.get("explanation", f"Generated by {model}.")


def _llm_sql(question: str, df, limit: int) -> tuple[str, str]:
    load_env_file()

    api_key = os.getenv("AI_AGENT_API_KEY") or os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise HTTPException(
            status_code=400,
            detail="LLM agent is not configured. Set AI_AGENT_API_KEY or OPENAI_API_KEY in your .env file.",
        )

    base_url = os.getenv("AI_AGENT_BASE_URL") or os.getenv("OPENAI_BASE_URL") or "https://api.openai.com/v1"
    model = os.getenv("AI_AGENT_MODEL") or os.getenv("OPENAI_MODEL") or "gpt-4.1-mini"
    max_tokens = min(int(os.getenv("AI_AGENT_MAX_TOKENS", "160")), 220)
    timeout_seconds = min(float(os.getenv("AI_AGENT_TIMEOUT_SECONDS", "15")), 20)
    reasoning_effort = os.getenv("AI_AGENT_REASONING_EFFORT")
    endpoint = base_url.rstrip("/") + "/chat/completions"

    prompt = (
        'Return JSON only: {"sql":"...","explanation":"..."}. '
        "Generate valid SQLite SELECT for table data. "
        "The user may write Vietnamese, English, or mixed language. "
        "Available columns: "
        f"{_schema_text(df)}\n"
        "Rules: use exact column names and quote them with double quotes; "
        "every SQL statement must include FROM data; "
        'use valid aggregate syntax such as MAX("Column"), MIN("Column"), AVG("Column"), SUM("Column"), COUNT(*); '
        "map plurals or minor wording differences to the closest available column; "
        "no semicolon, comments, DDL, DML, PRAGMA, joins, or multiple statements; "
        f"add LIMIT only when returning raw rows, max {limit} rows.\n"
        f"Question: {question}"
    )

    errors = []
    for candidate_model in _configured_models(model):
        try:
            return _request_llm_sql(
                endpoint=endpoint,
                api_key=api_key,
                model=candidate_model,
                prompt=prompt,
                max_tokens=max_tokens,
                timeout_seconds=timeout_seconds,
                reasoning_effort=reasoning_effort,
            )
        except Exception as exc:
            errors.append(str(exc))

    raise RuntimeError(" | ".join(errors))


def _parse_json_content(content: str) -> dict:
    cleaned = content.strip()

    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, flags=re.DOTALL)

        if not match:
            raise

        return json.loads(match.group(0))


def query_dataset_with_agent(file_path: str, question: str, limit: int = 200) -> dict[str, Any]:
    capped_limit = max(1, min(limit, 200))
    df = _read_dataset(file_path)
    config = get_agent_config()

    if not config["configured"]:
        raise HTTPException(
            status_code=400,
            detail="LLM agent is not configured. Set AI_AGENT_API_KEY or OPENAI_API_KEY in your .env file.",
        )

    try:
        sql, explanation = _llm_sql(question, df, capped_limit)
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"LLM SQL generation failed: {exc}") from exc

    safe_sql = validate_select_sql(sql, capped_limit)

    with sqlite3.connect(":memory:") as connection:
        df.to_sql("data", connection, if_exists="replace", index=False)
        connection.row_factory = sqlite3.Row

        try:
            cursor = connection.execute(safe_sql)
            rows = [dict(row) for row in cursor.fetchall()]
        except sqlite3.Error as exc:
            raise HTTPException(status_code=400, detail=f"SQL execution failed: {exc}") from exc

    return {
        "question": question,
        "sql": safe_sql,
        "explanation": explanation,
        "generated_by": "llm",
        "llm_configured": config["configured"],
        "llm_error": None,
        "columns": list(rows[0].keys()) if rows else [],
        "rows": rows,
        "row_count": len(rows),
    }
